cooperative_finance/urls.py
from django.contrib import admin
from django.urls import path,include
import static_pages.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('static_pages/', include('static_pages.urls')),
    path('about/', static_pages.views.about, name="about"),
    path('contact/', static_pages.views.contact, name="contact"),
    path('savings/', include('savings.urls')),
    path('loans/', include('loans.urls')),
    path('shares/', include('shares.urls')),
    path('', include('members.urls')),
    path('reports/', include('reports.urls')),
    path('accounting/', include('accounting.urls')),
    path('search/', include('search.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loans/urls.py
from django.urls import path

from .views import (loan_issue,loan_payment,
                    loan_issue_transactions,loan_payment_transactions,
                    loan_issue_transaction,loan_payment_transaction,
                    loan_approve,loan_account,loan,
                    get_loan,loan_issue_delete,
                    loan_payment_delete,get_loan_account)

app_name = 'loans'

urlpatterns = [
    path('', loan, name='loan'),
    path('get', get_loan_account, name='get_loan_account'),
    path('de|activate/', loan_account, name='de|activate'),
    path('pay/', loan_payment, name='pay'),
    path('pay/<int:pk>/', loan_payment, name='paypk'),
    path('pay/<int:pk>/delete', loan_payment_delete, name='payment_delete'),
    path('issue/', loan_issue, name='issue'),
    path('issue/<int:pk>/', loan_issue, name='issuepk'),
    path('issue/<int:pk>/delete', loan_issue_delete, name='issue_delete'),
    path('issue/get/', get_loan, name='get_loan'),
    path('issue/get/<int:pk>/', get_loan, name='get_loanpk'),
    path('issue/approve/', loan_approve, name='approve'),
    path('issue/approve/<int:loan_num>/', loan_approve, name='approveloan_num'),
    path('pay/transactions/', loan_payment_transactions, name='transactions'),
    path('issue/transactions/', loan_issue_transactions, name='issue_transactions'),
    path('pay/transaction/', loan_payment_transaction, name='transaction'),
    path('issue/transaction/', loan_issue_transaction, name='issue_transaction'),
]

loans/models.py
from django.db import models
from members.models import Member
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

STATUS_CHOICE = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        )

ACCOUNT_STATUS_CHOICE = (
       	('Deactivated', 'Deactivated'),
        ('Activated', 'Activated'),
        )

DELETE_STATUS_CHOICE = (
        ('False', 'False'),
        ('True', 'True'),
        )


LOAN_TYPE_CHOICES = [
    ('Loan', 'Loan'),
    ('Interest', 'Interest'),
    ('Commodity', 'Commodity'),
]


class LoanAccount(models.Model):
    owner = models.OneToOneField(Member, on_delete=models.CASCADE, related_name='loan_account')
    loan_type = models.CharField(choices=LOAN_TYPE_CHOICES, max_length=20, default='Loan')
    loan = models.PositiveIntegerField()
    debit = models.PositiveIntegerField(default=0)
    credit = models.PositiveIntegerField(default=0)
    status = models.CharField(choices=ACCOUNT_STATUS_CHOICE, default='Activated', max_length=11)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.owner.first_name

class LoanIssue(models.Model):
    account = models.ForeignKey(LoanAccount, on_delete=models.CASCADE)
    loan_num = models.CharField(unique=True, max_length=255, editable=False, default="")
    principal = models.PositiveIntegerField()
    status = models.CharField(choices=STATUS_CHOICE, default='Pending', max_length=15)
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        add = not self.pk
        super(LoanIssue, self).save(*args, **kwargs)
        if add:
            date = self.date_created.strftime("%y%m%d")
            if self.pk < 10:
                pk = "0" + str(self.pk)
            else:
                pk = str(self.pk)
            self.loan_num = date + pk
            kwargs["force_insert"] = False
            super(LoanIssue, self).save(*args, **kwargs)


    def __str__(self):
        return self.account.owner.first_name

class LoanPayment(models.Model):
    loan_num = models.ForeignKey(LoanIssue, on_delete=models.CASCADE)
    principal = models.PositiveIntegerField()
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.loan_num.account.owner.first_name

class LoansIssue(models.Model):
    account = models.ForeignKey(LoanAccount, on_delete=models.CASCADE)
    loan_num = models.CharField(unique=True, max_length=255)
    principal = models.PositiveIntegerField()
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.account.owner.first_name

    class Meta:
        verbose_name_plural = "Loans issued"


# @receiver(post_save, sender=Member)
# def create_account(sender, **kwargs):
#     if kwargs['created']:
#         LoanAccount.objects.create(owner=kwargs['instance'])

loans/forms.py
from django import forms
from members.models import Member
from .models import (LoanIssue,LoanPayment,LoanAccount)

class LoanAccountForm(forms.ModelForm):
    class Meta:
        model = LoanAccount
        fields = ('owner', 'loan_type', 'loan', 'debit', 'credit')
    
    def clean(self):
        cleaned_data = super().clean()
        # No need to check for existing SavingAccount here
        return cleaned_data
        
    def __init__(self, *args, **kwargs):
        super(LoanAccountForm, self).__init__(*args, **kwargs)
        # Filter the owner field to exclude members who are staff or superusers
        self.fields['owner'].queryset = Member.objects.exclude(is_staff=True, is_superuser=True)

class LoanIssueForm(forms.ModelForm):
    class Meta:
        model = LoanIssue
        fields = ('__all__')

class LoanPaymentForm(forms.ModelForm):
    class Meta:
        model = LoanPayment
        fields = ('__all__')

class GetLoanNumForm(forms.ModelForm):
    class Meta:
        model = LoanPayment
        fields = ('loan_num',)

class GetLoanAccountForm(forms.ModelForm):
    class Meta:
        model = LoanIssue
        fields = ('account',)

loans/views.py
from django.shortcuts import (render, redirect,
        get_object_or_404)
from django.contrib import messages
from django.db.models import Sum
from django import forms

from .forms import (LoanIssueForm,LoanPaymentForm,
       GetLoanNumForm,LoanAccountForm,GetLoanAccountForm)

from .models import (LoanAccount,LoanIssue,
    LoanPayment,LoansIssue)

from accounting.models import Income,IncomeType

# Create your views here.

# for charging loan fee by default look at loan_approve function
LOAN_FEE_PK = 1
LOAN_FEE_PERCENT = 2

def loan_account(request):
    template = 'loans/loans_form.html'

    pk = request.session['ordered_loans_pk']
    print(pk)
    print("*************")

    ordered_loan_ac = get_object_or_404(LoanAccount, pk=pk)

    if request.method == 'POST':
        form = LoanAccountForm(request.POST, instance=ordered_loan_ac)
    else:
        form = LoanAccountForm(instance=ordered_loan_ac)

    if form.is_valid():
        form.save()
        return redirect('loans:loan')

    context = {
            'form': form,
            'title': "Loan",
            }

    return render(request, template, context)


def loan_issue(request, **kwargs):
    template = 'loans/loans_form.html'

    if request.method == "POST":
        form = LoanIssueForm(request.POST)
        if form.is_valid():
            issue = form.save(commit=False)
            if issue.account.status == 'Deactivated':
                messages.warning(request,
                        "This account is not yet activated please activate the account first")
                return redirect("loans:loan")

            if issue.status == 'Approved':
            #adds issued principal to the users account total principal
                issue.account.total_principal += issue.principal
                issue.account.save()
            issue.save()
            messages.success(request,
                        'You have successfully issued Rs. {} only loan to the account number {}.'
                        .format(issue.principal,issue.account.owner.mem_number))
            if 'pk' in kwargs:
                return redirect("loans:issuepk", pk=kwargs['pk'])
            return redirect("loans:issue")
    else:
        if 'pk' in kwargs:
            ac = kwargs['pk']
            form = LoanIssueForm()
            form.fields["account"].queryset = LoanAccount.objects.filter(id=ac)
            form.fields["account"].initial = ac
            form.fields["account"].widget = forms.HiddenInput()
        else:
            form = LoanIssueForm()

    context = {
        'form': form,
        'title': "Issue",
    }

    return render(request, template, context)



def loan_payment(request, **kwargs):
    if request.method == "POST":
        owner_id = request.POST.get('owner')
        loan_account = LoanAccount.objects.filter(owner_id=owner_id).first()

        if loan_account:
            form = LoanAccountForm(request.POST, instance=loan_account)
        else:
            form = LoanAccountForm(request.POST)

        if form.is_valid():
            payment = form.save(commit=False)
            if payment.status == 'Deactivated':
                messages.warning(request, "This account is not yet activated, please activate the account first.")
                return redirect("loans:loan")

            # Additional logic to handle payment
            payment.debit += payment.loan  # Example logic for handling loan payment
            payment.save()

            messages.success(request, 'Loan account successfully updated or created.')
            form = LoanAccountForm()  # Reset the form after saving
        else:
            print("Form Errors:", form.errors)
            print("Form Data:", request.POST)
            messages.error(request, 'There was an error with your submission. Please correct the errors below.')
    else:
        form = LoanAccountForm()

    return render(request, 'loans/loans_form.html', {'form': form, 'title': "Record Loan"})




def loan_issue_transactions(request):
    template = 'loans/loans_transactions.html'

    loans = LoanIssue.objects.filter(status='Approved',delete_status = False)
    loans_sum = loans.aggregate(Sum('principal'))['principal__sum']

    context = {
        'transactions': loans,
        'transactions_sum': loans_sum,
        'title': "Issue",
    }

    return render(request, template, context)

def loan_payment_transactions(request):
    template = 'loans/loans_transactions.html'

    # Assuming you want to display the sum of the loan amounts
    loans = LoanAccount.objects.filter(owner__is_staff=False, owner__is_superuser=False)
    loans_sum = loans.aggregate(Sum('loan'))['loan__sum']

    context = {
        'transactions': loans,
        'transactions_sum': loans_sum,
        'title': "Loan",
    }

    return render(request, template, context)


def get_loan_account(request):
    template = 'loans/loans_form.html'

    form = GetLoanAccountForm(request.POST or None)

    if form.is_valid():
        loans_account = form.save(commit=False)
        pk = loans_account.account.pk
        request.session['ordered_loans_pk']=pk
        return redirect("loans:de|activate")

    context = {
        'form': form,
        'title': 'de|activate',
        }

    return render(request, template, context)

def loan_issue_transaction(request):
    template = 'loans/loans_transactions.html'

    form = GetLoanNumForm(request.POST or None)

    if form.is_valid():
        ordered_loan = form.save(commit=False)
        loans = LoanIssue.objects.filter(loan_num = ordered_loan.loan_num.loan_num, delete_status = False)
        loans_sum = loans.aggregate(Sum('principal'))['principal__sum']
        messages.success(request,
                        'Loan Issue loans of loan number {}.'
                        .format(ordered_loan.loan_num))

        context = {
            'transactions': loans,
            'transactions_sum': loans_sum,
            'title': 'Issued',
        }
        return render(request, template, context)
    context = {
        'form':form,
        'title':"Issued",
    }

    return render(request, template, context)

def loan_payment_transaction(request):
    template = 'loans/loans_transactions.html'

    form = GetLoanNumForm(request.POST or None)

    if form.is_valid():
        ordered_loan = form.save(commit=False)
        loans = LoanPayment.objects.filter(loan_num = ordered_loan.loan_num, delete_status = False)
        loans_sum = loans.aggregate(Sum('principal'))['principal__sum']
        messages.success(request,
                         'Loan Payment loans of loan number {}.'
                         .format(ordered_loan.loan_num))

        context = {
            'transactions': loans,
            'transactions_sum': loans_sum,
            'title': "Payment",
        }

        return render(request, template, context)

    context = {
        'form': form,
        'title': "Payment",
    }

    return render(request, template, context)

def get_loan(request, **kwargs):
    template = 'loans/loans_form.html'

    if 'pk' in kwargs:
        loan_ac = kwargs['pk']
        form = GetLoanNumForm(request.POST or None)
        form.fields["loan_num"].queryset = LoanIssue.objects.filter(account=loan_ac, status="Pending")
    else:
        form = GetLoanNumForm(request.POST or None)
        form.fields["loan_num"].queryset = LoanIssue.objects.filter(status="Pending")

    if form.is_valid():
        loan = form.save(commit=False)
        if loan.loan_num.status == 'Approved':
            messages.success(
                request,
                'This loan is already approved')
            if 'pk' in kwargs:
                return redirect("loans:get_loanpk", pk=kwargs['pk'])
            else:
                return redirect("loans:get_loan")

        loan_num = loan.loan_num.loan_num
        request.session['loan_num']=loan_num
        return redirect("loans:approve")

    context = {
        'form': form,
        'title': "approve",
    }
    return render(request, template, context)

def loan_approve(request, **kwargs):
    template = 'loans/loans_form.html'

    if 'loan_num' in kwargs:
        loan_num = kwargs['loan_num']
    else:
        loan_num = request.session['loan_num']

    ordered_loan = get_object_or_404(LoanIssue, loan_num = loan_num)

    if request.method == "POST":
        form = LoanIssueForm(request.POST, instance=ordered_loan)
    else:
        form = LoanIssueForm(instance=ordered_loan)

    if form.is_valid():
        issue = form.save(commit=False)
        if issue.account.status == 'Deactivated':
            messages.warning(request,
                        "This account is not yet activated please activate the account first")
            return redirect("loans:loan")
        #adds issued principal to the users total_principal of loan ac
        income_type = get_object_or_404(IncomeType, pk=LOAN_FEE_PK)
        Income.objects.create(amount=LOAN_FEE_PERCENT/100*issue.principal, received_from=issue.account.owner, loan_num=issue, income_type=income_type)
        issue.account.total_principal += issue.principal
        issue.account.save()
        issue.save()
        if issue.status == 'Approved':
            LoansIssue.objects.create(account = issue.account, loan_num = issue.loan_num, principal = issue.principal)
            messages.success(
                    request,
                    'You have issued')
        else:
            messages.warning(
                    request,
                    'Loan is not yet approved')
        #if request.session:
            #del request.session['loan_num']
        if 'loan_num' in kwargs:
            issue_instance=get_object_or_404(LoanIssue, loan_num=kwargs['loan_num'])
            mem_number=issue_instance.account.owner.mem_number
            return redirect("members:member_detail", mem_number=mem_number)
        return redirect("loans:get_loan")

    context = {
        'form': form,
        'title': "confirm",
    }

loans/templates/loans/loans.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">

	{% if messages %}
	{% for message in messages %}
	<p>{{message}}</p>
	{% endfor %}
	{% endif %}

	<h2 class="text-center">Loans Account Management</h2>
	<div class="row p-3 mt-3">
		<div class="col-md-6">
			<h4>Operations</h4>
			<h3><a hx-get="{% url 'loans:pay' %}" hx-target="#dynamic-content" class="btn btn-outline-info">Loan</a></h3>
			<h3><a href="{% url 'loans:issue' %}">Issue</a></h3>
			<h3><a href="{% url 'loans:get_loan' %}">Approve</a></h3>
			<h3><a href="{% url 'loans:get_loan_account' %}">de|activate</a></h3>
		</div>
		<div class="col-md-6">
			<h4>Transactions</h4>
			<h3><a hx-get="{% url 'loans:transactions' %}" hx-target="#dynamic-content" class="btn btn-outline-primary">All Loan Pay Transactions</a></h3>
			<h3><a href="{% url 'loans:transaction' %}">Single Loan account Transactions</a></h3>
			<h3><a href="{% url 'loans:issue_transactions' %}">All Loan Issue Transactions</a></h3>
			<h3><a href="{% url 'loans:issue_transaction' %}">Single account Loan Issue Transactions</a></h3>
		</div>
	</div>
</div>

{% endblock %}

loans/templates/loans/loans_delete.html
{% extends 'base.html' %}

{% block content %}

<p>Are you sure if you want to delete {{item.account}} loans {{type}} transaction with amount {{item.principal}} and loan num {{item.loan_num}}</p>

<form method="POST">
  {% csrf_token %}
  <input type="hidden" name="previous" value="{{request.GET.previous}}">
  <button type="submit">Confirm</button>
</form>

{% endblock %}

loans/templates/loans/loans_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4 text-center">{{ title }}</h2>

    {% if messages %}
        <div class="alert alert-info">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <form method="POST" class="form-horizontal" hx-post="{% url 'loans:pay' %}" hx-target="#dynamic-content" 
      hx-swap="innerHTML">
        {% csrf_token %}

        <div class="form-group">
            <label for="owner">Select User</label>
            {% render_field form.owner class="form-control" %}
        </div>

        <div class="form-group">
            <label for="loan_type">Loan Type</label>
            {% render_field form.loan_type class="form-control" %}
        </div>

        <div class="form-group">
            <label for="loan">Loan Amount</label>
            {% render_field form.loan class="form-control" %}
        </div>

        <div class="form-group">
            <label for="debit">Debit</label>
            {% render_field form.debit class="form-control" %}
        </div>

        <div class="form-group">
            <label for="credit">Credit</label>
            {% render_field form.credit class="form-control" %}
        </div>

        <div class="form-group text-center">
            <input type="submit" value="{{ title }}" class="btn btn-primary btn-lg" />
        </div>
    </form>
</div>
{% endblock %}

loans/templates/loans/loans_transactions.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    {% if form %}
    <form method="POST" class="form-horizontal">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-center">
            <input type="submit" value="View" class="btn btn-primary btn-lg" />
        </div>
    </form>

    {% else %}
    {% if messages %}
    <div class="alert alert-info">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <h3 class="text-center">{{ title }} Transactions</h3>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Owner</th>
                    <th>Loan Type</th>
                    <th>Loan Amount</th>
                    <th>Debit</th>
                    <th>Credit</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ transaction.owner.first_name }} {{ transaction.owner.last_name }}</td>
                    <td>{{ transaction.loan_type }}</td>
                    <td>{{ transaction.loan }}</td>
                    <td>{{ transaction.debit }}</td>
                    <td>{{ transaction.credit }}</td>
                    <td>
                        <a href="#">Delete</a>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <th scope="row">Total</th>
                    <td colspan="3"></td>
                    <td>{{ transactions_sum }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <hr>
    {% endif %}
</div>
{% endblock %}