cooperative_finance/urls.py
from django.contrib import admin
from django.urls import path,include
import static_pages.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('static_pages/', include('static_pages.urls')),
    path('about/', static_pages.views.about, name="about"),
    path('contact/', static_pages.views.contact, name="contact"),
    path('savings/', include('savings.urls')),
    path('loans/', include('loans.urls')),
    path('shares/', include('shares.urls')),
    path('', include('members.urls')),
    path('reports/', include('reports.urls')),
    path('accounting/', include('accounting.urls')),
    path('search/', include('search.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loans/urls.py
from django.urls import path

from .views import (loan_issue,loan_payment,
                    loan_issue_transactions,loan_payment_transactions,
                    loan_issue_transaction,loan_payment_transaction,
                    loan_approve,loan_account,loan,
                    get_loan,loan_issue_delete,
                    loan_payment_delete,get_loan_account)

app_name = 'loans'

urlpatterns = [
    path('', loan, name='loan'),
    path('get', get_loan_account, name='get_loan_account'),
    path('de|activate/', loan_account, name='de|activate'),
    path('pay/', loan_payment, name='pay'),
    path('pay/<int:pk>/', loan_payment, name='paypk'),
    path('pay/<int:pk>/delete', loan_payment_delete, name='payment_delete'),
    path('issue/', loan_issue, name='issue'),
    path('issue/<int:pk>/', loan_issue, name='issuepk'),
    path('issue/<int:pk>/delete', loan_issue_delete, name='issue_delete'),
    path('issue/get/', get_loan, name='get_loan'),
    path('issue/get/<int:pk>/', get_loan, name='get_loanpk'),
    path('issue/approve/', loan_approve, name='approve'),
    path('issue/approve/<int:loan_num>/', loan_approve, name='approveloan_num'),
    path('pay/transactions/', loan_payment_transactions, name='transactions'),
    path('issue/transactions/', loan_issue_transactions, name='issue_transactions'),
    path('pay/transaction/', loan_payment_transaction, name='transaction'),
    path('issue/transaction/', loan_issue_transaction, name='issue_transaction'),
]

reports/urls.py
from django.urls import path
from .views import (report,income,expense,loan,capital,
monthly,yearly,delete_transaction, bulk_delete_records, 
delete_month_records, delete_year_records)
app_name = 'reports'
urlpatterns = [
    path('', report, name='reports'),
    path('income', income, name='income'),
    path('expense', expense, name='expense'),
    path('loans', loan, name='loan'),
    path('capital', capital, name='capital'),
    path('reports/monthly/', monthly, name='monthly'),
    path('reports/yearly/', yearly, name='yearly'),
    path('delete_transaction/<int:transaction_id>/', delete_transaction, name='delete_transaction'),
        path('bulk-delete/', bulk_delete_records, name='bulk_delete_records'),
    path('delete-month/<int:month>/<int:year>/', delete_month_records, name='delete_month_records'),
    path('delete-year/<int:year>/', delete_year_records, name='delete_year_records'),
]

loans/models.py
from django.db import models
from members.models import Member
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

STATUS_CHOICE = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        )

ACCOUNT_STATUS_CHOICE = (
       	('Deactivated', 'Deactivated'),
        ('Activated', 'Activated'),
        )

DELETE_STATUS_CHOICE = (
        ('False', 'False'),
        ('True', 'True'),
        )


LOAN_TYPE_CHOICES = [
    ('Loan', 'Loan'),
    ('Interest', 'Interest'),
    ('Commodity', 'Commodity'),
]


class LoanAccount(models.Model):
    owner = models.OneToOneField(Member, on_delete=models.CASCADE, related_name='loan_account')
    loan_type = models.CharField(choices=LOAN_TYPE_CHOICES, max_length=20, default='Loan')
    loan = models.PositiveIntegerField()
    debit = models.PositiveIntegerField(default=0)
    credit = models.PositiveIntegerField(default=0)
    status = models.CharField(choices=ACCOUNT_STATUS_CHOICE, default='Activated', max_length=11)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.owner.first_name

class LoanIssue(models.Model):
    account = models.ForeignKey(LoanAccount, on_delete=models.CASCADE)
    loan_num = models.CharField(unique=True, max_length=255, editable=False, default="")
    principal = models.PositiveIntegerField()
    status = models.CharField(choices=STATUS_CHOICE, default='Pending', max_length=15)
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        add = not self.pk
        super(LoanIssue, self).save(*args, **kwargs)
        if add:
            date = self.date_created.strftime("%y%m%d")
            if self.pk < 10:
                pk = "0" + str(self.pk)
            else:
                pk = str(self.pk)
            self.loan_num = date + pk
            kwargs["force_insert"] = False
            super(LoanIssue, self).save(*args, **kwargs)


    def __str__(self):
        return self.account.owner.first_name

class LoanPayment(models.Model):
    loan_num = models.ForeignKey(LoanIssue, on_delete=models.CASCADE)
    principal = models.PositiveIntegerField()
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.loan_num.account.owner.first_name

class LoansIssue(models.Model):
    account = models.ForeignKey(LoanAccount, on_delete=models.CASCADE)
    loan_num = models.CharField(unique=True, max_length=255)
    principal = models.PositiveIntegerField()
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.account.owner.first_name

    class Meta:
        verbose_name_plural = "Loans issued"


# @receiver(post_save, sender=Member)
# def create_account(sender, **kwargs):
#     if kwargs['created']:
#         LoanAccount.objects.create(owner=kwargs['instance'])

reports/models.py
from django.db import models

# Create your models here.

savings/models.py
from django.db import models
from members.models import Member
from django.dispatch import receiver
from django.db.models.signals import post_save
import datetime


# Create your models here.

ACCOUNT_STATUS_CHOICE = (
        ('Deactivated', 'Deactivated'),
        ('Activated', 'Activated'),
        )

DELETE_STATUS_CHOICE = (
        ('False', 'False'),
        ('True', 'True'),
        )


SAVING_TYPE_CHOICES = [
    ('Oracle', 'Oracle'),
    ('Teller', 'Teller'),
]

MONTH_CHOICES = [
    (1, "January"), (2, "February"), (3, "March"), (4, "April"),
    (5, "May"), (6, "June"), (7, "July"), (8, "August"),
    (9, "September"), (10, "October"), (11, "November"), (12, "December")
]

YEAR_CHOICES = [(r, r) for r in range(2000, datetime.date.today().year+1)]


class SavingAccount(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='saving_accounts')
    received = models.PositiveIntegerField(default=0)
    
    # Existing fields
    savings = models.PositiveIntegerField(default=0)
    divine_touch = models.PositiveIntegerField(default=0)
    rss = models.PositiveIntegerField(default=0)
    loan_repay = models.PositiveIntegerField(default=0)
    interest_repay = models.PositiveIntegerField(default=0)
    commod_repay = models.PositiveIntegerField(default=0)
    loan = models.PositiveIntegerField(default=0)
    interest = models.PositiveIntegerField(default=0)
    commod = models.PositiveIntegerField(default=0)
    share = models.PositiveIntegerField(default=0)
    
    # New balance fields
    savings_balance = models.PositiveIntegerField(default=0)
    interest_balance = models.PositiveIntegerField(default=0)
    loan_balance = models.PositiveIntegerField(default=0)
    commodity_balance = models.PositiveIntegerField(default=0)
    rss_balance = models.PositiveIntegerField(default=0)
    divine_touch_balance = models.PositiveIntegerField(default=0)
    share_balance = models.PositiveIntegerField(default=0)
    
    month = models.IntegerField(choices=MONTH_CHOICES, default=datetime.date.today().month)
    year = models.IntegerField(choices=YEAR_CHOICES, default=datetime.date.today().year)
    status = models.CharField(choices=ACCOUNT_STATUS_CHOICE, default='Activated', max_length=11)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)



class LoanAccount(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='loan_accounts')
    loan = models.PositiveIntegerField(default=0)  # You can replace this with your choices
    loan_balance = models.PositiveIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.owner.first_name} {self.owner.last_name} - Loan Account"


class InterestAccount(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='interest_accounts')
    interest = models.PositiveIntegerField(default=0)
    interest_balance = models.PositiveIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.owner.first_name} {self.owner.last_name} - Interest Account"


class CommodityAccount(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='commodity_accounts')
    commod = models.PositiveIntegerField(default=0)
    commod_balance = models.PositiveIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.owner.first_name} {self.owner.last_name} - Commodity Account"


class SavingDeposit(models.Model):
    account = models.ForeignKey(SavingAccount, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.account.owner.first_name

class SavingWithdrawal(models.Model):
    account = models.ForeignKey(SavingAccount, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.account.owner.first_name

@receiver(post_save, sender=Member)
def create_account(sender, **kwargs):
    if kwargs['created']:
        # Remove the current_balance argument
        SavingAccount.objects.create(owner=kwargs['instance'])

loans/forms.py
from django import forms
from members.models import Member
from .models import (LoanIssue,LoanPayment,LoanAccount)

class LoanAccountForm(forms.ModelForm):
    class Meta:
        model = LoanAccount
        fields = ('owner', 'loan_type', 'loan', 'debit', 'credit')
    
    def clean(self):
        cleaned_data = super().clean()
        # No need to check for existing SavingAccount here
        return cleaned_data
        
    def __init__(self, *args, **kwargs):
        super(LoanAccountForm, self).__init__(*args, **kwargs)
        # Filter the owner field to exclude members who are staff or superusers
        self.fields['owner'].queryset = Member.objects.exclude(is_staff=True, is_superuser=True)

class LoanIssueForm(forms.ModelForm):
    class Meta:
        model = LoanIssue
        fields = ('__all__')

class LoanPaymentForm(forms.ModelForm):
    class Meta:
        model = LoanPayment
        fields = ('__all__')

class GetLoanNumForm(forms.ModelForm):
    class Meta:
        model = LoanPayment
        fields = ('loan_num',)

class GetLoanAccountForm(forms.ModelForm):
    class Meta:
        model = LoanIssue
        fields = ('account',)

reports/templates/reports/_capital.html
<h1>{{title_capital}} Report</h1>

<h2>{{title_capital}} Additions</h2>
<table>
	<colspan>
		<col width=50%>
		<col width=50%>
	</colspan>
	<tr>
		<th>Type</th>
		<th>Amount</th>
	</tr>
	<tr>
		<td>Shares out</td>
		<td>{{shares_buy_sum_capital}}</td>
	</tr>
	<tr>
		<td>Saving Deposit</td>
		<td>{{savings_deposit_sum_capital}}</td>
	</tr>
	<tr>
		<td>Loan Recoveries</td>
		<td>{{loan_payment_sum_capital}}</td>
	</tr>
	<tr>
		<td>Total Capital Additions: {{total_capital_additions}}</td>
	</tr>
</table>

<h2>{{title_capital}} Deductions</h2>
<table>
	<colspan>
		<col width=50%>
		<col width=50%>
	</colspan>
	<tr>
		<th>Type</th>
		<th>Amount</th>
	</tr>
	<tr>
		<td>Shares In</td>
		<td>{{shares_sell_sum_capital}}</td>
	</tr>
	<tr>
		<td>Saving withdrawals</td>
		<td>{{savings_withdrawal_sum_capital}}</td>
	</tr>
	<tr>
		<td>Loans out</td>
		<td>{{loans_issued_sum_capital}}</td>
	</tr>
	<tr>
		<td>Total Capital Deductions: {{total_capital_deductions}}</td>
	</tr>
</table>

reports/templates/reports/_form_year.html
<form method="POST">
	{% csrf_token %}
	<p>Year: <input type='number' name='year' value='2019'> <button type="submit">Submit</button></p>
</form>

reports/templates/reports/_form_year_month.html
<form method="POST">
	{% csrf_token %}
	<p>month<input type='number' name='month' value='08'> Year: <input type='number' name='year' value='2019'> <button type="submit">Submit</button></p>
</form>

reports/templates/reports/bulk_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-12">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0"><i class="fas fa-trash-alt me-2"></i>Bulk Record Deletion</h4>
                </div>
                <div class="card-body">
                    <!-- Information Alert -->
                    <div class="alert alert-info">
                        <h5 class="alert-heading"><i class="fas fa-info-circle me-2"></i>Important Information</h5>
                        <p class="mb-2">This page allows you to delete records in bulk by month or year.</p>
                        <p class="mb-0">
                            <strong>To delete individual records:</strong> Please go to the 
                            <a hx-get="{% url 'reports:monthly' %}" hx-target="#dynamic-content" class="btn btn-outline-info">Monthly Report</a>
                            <!-- <a hx-get="{% url 'reports:yearly' %}" hx-target="#dynamic-content" class="btn btn-outline-info">Yearly Report</a>  -->
                            page and use the delete option next to each record.
                        </p>
                    </div>

                    <!-- Warning Alert -->
                    <div class="alert alert-warning">
                        <h5 class="alert-heading"><i class="fas fa-exclamation-triangle me-2"></i>Warning</h5>
                        <p class="mb-0">Bulk deletion is permanent and cannot be undone. Please be certain before proceeding.</p>
                    </div>

                    {% if months_with_records %}
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead class="table-dark">
                                <tr>
                                    <th>Month/Year</th>
                                    <th>Number of Records</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for record in months_with_records %}
                                <tr>
                                    <td>
                                        <strong>{{ record.month_name }} {{ record.year }}</strong>
                                    </td>
                                    <td>
                                        <span class="badge bg-primary rounded-pill">{{ record.record_count }}</span>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteMonthModal{{ record.month }}_{{ record.year }}">
                                            <i class="fas fa-trash me-1"></i> Delete Month
                                        </button>
                                    </td>
                                </tr>
                                
                                <!-- Delete Month Modal -->
                                <div class="modal fade" id="deleteMonthModal{{ record.month }}_{{ record.year }}" tabindex="-1" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header bg-danger text-white">
                                                <h5 class="modal-title">Confirm Deletion</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <p>Are you sure you want to delete all <strong>{{ record.record_count }}</strong> records for <strong>{{ record.month_name }} {{ record.year }}</strong>?</p>
                                                <p class="text-danger"><strong>This action cannot be undone.</strong></p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                <form method="POST" action="{% url 'reports:delete_month_records' record.month record.year %}">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="confirm_delete" value="true">
                                                    <button type="submit" class="btn btn-danger">Delete All Records</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <!-- Yearly Summary Section -->
                    <div class="mt-5">
                        <h5 class="border-bottom pb-2">Delete by Year</h5>
                        <div class="row">
                            {% for year_record in years_with_counts %}
                            <div class="col-md-3 col-sm-6 mb-3">
                                <div class="card">
                                    <div class="card-body text-center">
                                        <h6 class="card-title">Year {{ year_record.year }}</h6>
                                        <p class="card-text">
                                            <span class="badge bg-info">{{ year_record.record_count }} records</span>
                                        </p>
                                        <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteYearModal{{ year_record.year }}">
                                            <i class="fas fa-trash me-1"></i> Delete Year
                                        </button>
                                    </div>
                                </div>
                            </div>
                            
                            <!-- Delete Year Modal -->
                            <div class="modal fade" id="deleteYearModal{{ year_record.year }}" tabindex="-1" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header bg-danger text-white">
                                            <h5 class="modal-title">Confirm Year Deletion</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure you want to delete all <strong>{{ year_record.record_count }}</strong> records for the year <strong>{{ year_record.year }}</strong>?</p>
                                            <p class="text-danger"><strong>This action cannot be undone.</strong></p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                            <form method="POST" action="{% url 'reports:delete_year_records' year_record.year %}">
                                                {% csrf_token %}
                                                <input type="hidden" name="confirm_delete" value="true">
                                                <button type="submit" class="btn btn-danger">Delete All Year Records</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% else %}
                    <div class="text-center py-4">
                        <i class="fas fa-folder-open fa-3x text-muted mb-3"></i>
                        <h5>No records found</h5>
                        <p class="text-muted">There are no records available for deletion.</p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
// Function to show a Bootstrap toast notification
function showToast(message, type = 'info') {
    // Remove any existing toast containers
    $('.toast-container').remove();
    
    // Create toast container
    const toastContainer = $('<div>').addClass('toast-container position-fixed top-0 end-0 p-3');
    
    // Create toast element
    const toast = $('<div>').addClass('toast align-items-center text-white bg-' + type)
        .addClass(type === 'success' ? 'bg-success' : type === 'error' ? 'bg-danger' : 'bg-info')
        .attr('role', 'alert').attr('aria-live', 'assertive').attr('aria-atomic', 'true');
    
    // Create toast content
    const toastContent = $('<div>').addClass('d-flex');
    const toastBody = $('<div>').addClass('toast-body').text(message);
    const closeButton = $('<button>').addClass('btn-close btn-close-white me-2 m-auto')
        .attr('type', 'button').attr('data-bs-dismiss', 'toast').attr('aria-label', 'Close');
    
    // Assemble toast
    toastContent.append(toastBody).append(closeButton);
    toast.append(toastContent);
    toastContainer.append(toast);
    
    // Add to body and show
    $('body').append(toastContainer);
    
    // Initialize and show toast
    const bsToast = new bootstrap.Toast(toast);
    bsToast.show();
    
    // Remove toast after it's hidden
    toast.on('hidden.bs.toast', function () {
        toastContainer.remove();
    });
}

// Function to handle form submissions with AJAX
function handleDeleteForm(form, url) {
    form.on('submit', function(e) {
        e.preventDefault();
        
        // Show loading state
        const submitButton = form.find('button[type="submit"]');
        const originalText = submitButton.html();
        submitButton.prop('disabled', true).html('<span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> Processing...');
        
        // Send AJAX request
        $.ajax({
            url: url,
            type: 'POST',
            data: form.serialize(),
            success: function(response) {
                if (response.success) {
                    showToast(response.message, 'success');
                    // Close the modal
                    form.closest('.modal').modal('hide');
                    // Reload the page after a short delay to reflect changes
                    setTimeout(function() {
                        location.reload();
                    }, 2000);
                } else {
                    showToast(response.message, 'error');
                    submitButton.prop('disabled', false).html(originalText);
                }
            },
            error: function(xhr) {
                try {
                    const response = JSON.parse(xhr.responseText);
                    showToast(response.message, 'error');
                } catch (e) {
                    showToast('An error occurred while processing your request.', 'error');
                }
                submitButton.prop('disabled', false).html(originalText);
            }
        });
    });
}

// Initialize when document is ready
$(document).ready(function() {
    // Attach event handlers to all delete forms
    $('form[action*="delete-month"]').each(function() {
        handleDeleteForm($(this), $(this).attr('action'));
    });
    
    $('form[action*="delete-year"]').each(function() {
        handleDeleteForm($(this), $(this).attr('action'));
    });
});
</script>
{% endblock %}

reports/templates/reports/capital.html
{% extends 'base.html' %}

{% block content %}

{% include 'reports/_form_year_month.html' %}
{% include 'reports/_capital.html' %}

{% endblock %}

reports/templates/reports/reports.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <!-- Instructions Section -->
    <div class="alert alert-info mb-4">
        <strong>Instructions:</strong> 
        <span>
            <p>Here in the report, the balance of each member can be viewed, along with the amount inputted each month.</p>
        </span>
    </div>
  

<!-- <h3>Income Report: <a href="{%url 'reports:income'%}">Income</a></h3>
<h3>Expense Report: <a href="{%url 'reports:expense'%}">Expense</a></h3>
<h3>Loans Report: <a href="{%url 'reports:loan'%}">Loans</a></h3>
<h3>Capital Report: <a href="{%url 'reports:capital'%}">Capital</a></h3> -->
<h3>Monthly Report: <a hx-get="{%url 'reports:monthly'%}" hx-target="#dynamic-content" class="btn btn-outline-primary">Monthly</a></h3>
<h3 class="invisible">Yearly Report: <a hx-get="{%url 'reports:yearly'%}" hx-target="#dynamic-content" class="btn btn-outline-primary invisible">Yearly</a></h3>

</div>
{% endblock %}

reports/templates/reports/yearly.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2>Yearly Report</h2>
    <form method="POST" hx-post="{% url 'reports:monthly' %}" hx-target="#dynamic-content">
        {% csrf_token %}
        <div class="form-group">
            <label for="year">Select Year To Generate Record</label>
            <select class="form-control" id="year" name="year">
                {% for year in YEAR_CHOICES %}
                    <option value="{{ year.0 }}" {% if year.0 == selected_year %}selected{% endif %}>
                        {{ year.1 }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Generate Report</button>
    </form>

    <form method="post" action="{% url 'reports:monthly' %}" target="_blank">
        {% csrf_token %}
        <div class="form-group">
            <label for="year">Select Year To Download Records</label>
            <select class="form-control" id="year" name="year">
                {% for year in YEAR_CHOICES %}
                    <option value="{{ year.0 }}" {% if year.0 == selected_year %}selected{% endif %}>
                        {{ year.1 }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" name="download_pdf" class="btn btn-danger mt-2">Download PDF</button>
        <button type="submit" name="download_excel" class="btn btn-success mt-2">Download Excel</button>
    </form>

    <hr>

    <h4>Savings</h4>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Owner</th>
                    <th>Payment Type</th>
                    <th>Normal Savings</th>
                    <th>Divine Touch</th>
                    <th>SP Sav</th>
                    <th>RSS</th>
                    <th>Loan Repay</th>
                    <th>Interest</th>
                    <th>Commod</th>
                    <th>Received</th>
                    <th>Year</th>
                </tr>
            </thead>
            <tbody>
                {% for saving in savings %}
                    <tr>
                        <td>{{ saving.owner }}</td>
                        <td>{{ saving.payment_type }}</td>
                        <td>{{ saving.normal_savings }}</td>
                        <td>{{ saving.divine_touch }}</td>
                        <td>{{ saving.sp_sav }}</td>
                        <td>{{ saving.rss }}</td>
                        <td>{{ saving.loan_repay }}</td>
                        <td>{{ saving.interest }}</td>
                        <td>{{ saving.commod }}</td>
                        <td>{{ saving.received }}</td>
                        <td>{{ saving.year }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>
{% endblock %}