cooperative_finance/urls.py
from django.contrib import admin
from django.urls import path,include
import static_pages.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('static_pages/', include('static_pages.urls')),
    path('about/', static_pages.views.about, name="about"),
    path('contact/', static_pages.views.contact, name="contact"),
    path('savings/', include('savings.urls')),
    path('loans/', include('loans.urls')),
    path('shares/', include('shares.urls')),
    path('', include('members.urls')),
    path('reports/', include('reports.urls')),
    path('accounting/', include('accounting.urls')),
    path('search/', include('search.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loans/urls.py
from django.urls import path

from .views import (loan_issue,loan_payment,
                    loan_issue_transactions,loan_payment_transactions,
                    loan_issue_transaction,loan_payment_transaction,
                    loan_approve,loan_account,loan,
                    get_loan,loan_issue_delete,
                    loan_payment_delete,get_loan_account)

app_name = 'loans'

urlpatterns = [
    path('', loan, name='loan'),
    path('get', get_loan_account, name='get_loan_account'),
    path('de|activate/', loan_account, name='de|activate'),
    path('pay/', loan_payment, name='pay'),
    path('pay/<int:pk>/', loan_payment, name='paypk'),
    path('pay/<int:pk>/delete', loan_payment_delete, name='payment_delete'),
    path('issue/', loan_issue, name='issue'),
    path('issue/<int:pk>/', loan_issue, name='issuepk'),
    path('issue/<int:pk>/delete', loan_issue_delete, name='issue_delete'),
    path('issue/get/', get_loan, name='get_loan'),
    path('issue/get/<int:pk>/', get_loan, name='get_loanpk'),
    path('issue/approve/', loan_approve, name='approve'),
    path('issue/approve/<int:loan_num>/', loan_approve, name='approveloan_num'),
    path('pay/transactions/', loan_payment_transactions, name='transactions'),
    path('issue/transactions/', loan_issue_transactions, name='issue_transactions'),
    path('pay/transaction/', loan_payment_transaction, name='transaction'),
    path('issue/transaction/', loan_issue_transaction, name='issue_transaction'),
]

reports/urls.py
from django.urls import path
from .views import (report,income,expense,loan,capital,
monthly,yearly,delete_transaction, bulk_delete_records, 
delete_month_records, delete_year_records)
app_name = 'reports'
urlpatterns = [
    path('', report, name='reports'),
    path('income', income, name='income'),
    path('expense', expense, name='expense'),
    path('loans', loan, name='loan'),
    path('capital', capital, name='capital'),
    path('reports/monthly/', monthly, name='monthly'),
    path('reports/yearly/', yearly, name='yearly'),
    path('delete_transaction/<int:transaction_id>/', delete_transaction, name='delete_transaction'),
        path('bulk-delete/', bulk_delete_records, name='bulk_delete_records'),
    path('delete-month/<int:month>/<int:year>/', delete_month_records, name='delete_month_records'),
    path('delete-year/<int:year>/', delete_year_records, name='delete_year_records'),
]

savings/urls.py
from django.urls import path

from .views import (saving_deposit,saving_withdrawal,
        saving_deposit_transactions,saving_withdrawal_transactions,
        saving_deposit_transaction,saving_withdrawal_transaction,
        saving_account,saving,
        saving_deposit_delete,saving_withdrawal_delete,
        get_saving_account, teller_savings_transactions, 
        oracle_savings_transactions, monthly_savings_report, yearly_savings_report,
        generate_pdf, edit_saving_account, delete_transaction,
        download_all_savings_excel, download_all_savings_pdf, download_teller_savings_excel,
        download_teller_savings_pdf, download_oracle_savings_excel, download_oracle_savings_pdf,
        add_loan_account, add_interest_account, add_commodity_account, download_template,
        upload_savings)

app_name = 'savings'
urlpatterns = [
    path('', saving, name='saving'),
    path('get', get_saving_account, name='get_savings_account'),
    path('de|activate/', saving_account, name='de|activate'),
    path('deposit/', saving_deposit, name='deposit'),
    # path('deposit/<int:pk>/', saving_deposit, name='depositpk'),
    path('deposit/<int:pk>/delete/', saving_deposit_delete, name='deposit_delete'),
    path('withdraw/', saving_withdrawal, name='withdraw'),
    path('withdraw/<int:pk>/', saving_withdrawal, name='withdrawpk'),
    path('withdraw/<int:pk>/delete/', saving_withdrawal_delete, name='withdraw_delete'),
    path('deposit/transactions/', saving_deposit_transactions, name='transactions'),
    path('withdraw/transactions/', saving_withdrawal_transactions, name='withdraw_transactions'),
    path('deposit/transaction/', saving_deposit_transaction, name='transaction'),
    path('withdraw/transaction/', saving_withdrawal_transaction, name='withdraw_transaction'),
    path('teller-savings/', teller_savings_transactions, name='teller_savings_transactions'),
    path('oracle-savings/', oracle_savings_transactions, name='oracle_savings_transactions'),
    path('monthly/<int:month>/<int:year>/', monthly_savings_report, name='monthly'),
    path('yearly/<int:year>/', yearly_savings_report, name='yearly'),
    path('transactions/pdf/', generate_pdf, name='generate_pdf'),
    path('edit/', edit_saving_account, name='edit_saving_account'),
    path('delete/<int:pk>/', delete_transaction, name='delete_transaction'),
    # Download URLs for All Savings
    path('download/all/excel/', download_all_savings_excel, name='download_all_savings_excel'),
    path('download/all/pdf/', download_all_savings_pdf, name='download_all_savings_pdf'),

    # Download URLs for Teller Savings
    path('download/teller/excel/', download_teller_savings_excel, name='download_teller_savings_excel'),
    path('download/teller/pdf/', download_teller_savings_pdf, name='download_teller_savings_pdf'),

    # Download URLs for Oracle Savings
    path('download/oracle/excel/', download_oracle_savings_excel, name='download_oracle_savings_excel'),
    path('download/oracle/pdf/', download_oracle_savings_pdf, name='download_oracle_savings_pdf'),

    path('add-loan-account/', add_loan_account, name='add_loan_account'),
    path('add-interest-account/', add_interest_account, name='add_interest_account'),
    path('add-commodity-account/', add_commodity_account, name='add_commodity_account'),
    path('download-template/', download_template, name='download_template'),
    path('upload-savings/', upload_savings, name='upload_savings'),
]

savings/models.py
from django.db import models
from members.models import Member
from django.dispatch import receiver
from django.db.models.signals import post_save
import datetime


# Create your models here.

ACCOUNT_STATUS_CHOICE = (
        ('Deactivated', 'Deactivated'),
        ('Activated', 'Activated'),
        )

DELETE_STATUS_CHOICE = (
        ('False', 'False'),
        ('True', 'True'),
        )


SAVING_TYPE_CHOICES = [
    ('Oracle', 'Oracle'),
    ('Teller', 'Teller'),
]

MONTH_CHOICES = [
    (1, "January"), (2, "February"), (3, "March"), (4, "April"),
    (5, "May"), (6, "June"), (7, "July"), (8, "August"),
    (9, "September"), (10, "October"), (11, "November"), (12, "December")
]

YEAR_CHOICES = [(r, r) for r in range(2000, datetime.date.today().year+1)]


class SavingAccount(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='saving_accounts')
    received = models.PositiveIntegerField(default=0)
    
    # Existing fields
    savings = models.PositiveIntegerField(default=0)
    divine_touch = models.PositiveIntegerField(default=0)
    rss = models.PositiveIntegerField(default=0)
    loan_repay = models.PositiveIntegerField(default=0)
    interest_repay = models.PositiveIntegerField(default=0)
    commod_repay = models.PositiveIntegerField(default=0)
    loan = models.PositiveIntegerField(default=0)
    interest = models.PositiveIntegerField(default=0)
    commod = models.PositiveIntegerField(default=0)
    share = models.PositiveIntegerField(default=0)
    
    # New balance fields
    savings_balance = models.PositiveIntegerField(default=0)
    interest_balance = models.PositiveIntegerField(default=0)
    loan_balance = models.PositiveIntegerField(default=0)
    commodity_balance = models.PositiveIntegerField(default=0)
    rss_balance = models.PositiveIntegerField(default=0)
    divine_touch_balance = models.PositiveIntegerField(default=0)
    share_balance = models.PositiveIntegerField(default=0)
    
    month = models.IntegerField(choices=MONTH_CHOICES, default=datetime.date.today().month)
    year = models.IntegerField(choices=YEAR_CHOICES, default=datetime.date.today().year)
    status = models.CharField(choices=ACCOUNT_STATUS_CHOICE, default='Activated', max_length=11)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)



class LoanAccount(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='loan_accounts')
    loan = models.PositiveIntegerField(default=0)  # You can replace this with your choices
    loan_balance = models.PositiveIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.owner.first_name} {self.owner.last_name} - Loan Account"


class InterestAccount(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='interest_accounts')
    interest = models.PositiveIntegerField(default=0)
    interest_balance = models.PositiveIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.owner.first_name} {self.owner.last_name} - Interest Account"


class CommodityAccount(models.Model):
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='commodity_accounts')
    commod = models.PositiveIntegerField(default=0)
    commod_balance = models.PositiveIntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.owner.first_name} {self.owner.last_name} - Commodity Account"


class SavingDeposit(models.Model):
    account = models.ForeignKey(SavingAccount, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.account.owner.first_name

class SavingWithdrawal(models.Model):
    account = models.ForeignKey(SavingAccount, on_delete=models.CASCADE)
    amount = models.PositiveIntegerField()
    delete_status = models.CharField(choices=DELETE_STATUS_CHOICE, default='False', max_length=5, editable=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.account.owner.first_name

@receiver(post_save, sender=Member)
def create_account(sender, **kwargs):
    if kwargs['created']:
        # Remove the current_balance argument
        SavingAccount.objects.create(owner=kwargs['instance'])

savings/templates/savings/commodity_account_form.html
<form method="post" hx-post="{% url 'savings:add_commodity_account' %}" hx-target="#dynamic-content" 
    hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% if messages %}
    <div class="alert alert-success mt-2">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}

savings/templates/savings/edit_saving_account.html
{% extends 'base.html' %}

{% block content %}
<h3 class="mb-4">{{ title }}</h3>

<form method="get" hx-get="{% url 'savings:edit_saving_account' %}"  hx-target="#dynamic-content" 
    hx-swap="innerHTML">
    <div class="form-group">
        <label for="owner">Owner</label>
        <select name="owner" class="form-control" id="owner">
            {% for member in form.fields.owner.queryset %}
                <option value="{{ member.id }}">{{ member.first_name }} {{ member.last_name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="month">Month</label>
        <select name="month" class="form-control" id="month">
            {% for month in form.fields.month.choices %}
                <option value="{{ month.0 }}">{{ month.1 }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="year">Year</label>
        <select name="year" class="form-control" id="year">
            {% for year in form.fields.year.choices %}
                <option value="{{ year.0 }}">{{ year.1 }}</option>
            {% endfor %}
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Fetch Record</button>
</form>

{% if form.instance.pk %}
    <form method="post" hx-post="{% url 'savings:edit_saving_account' %}" hx-target="#dynamic-content" 
        hx-swap="innerHTML">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Save Changes</button>
    </form>
{% endif %}

{% if messages %}
    <div class="alert alert-info">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}


{% endblock content %}

savings/templates/savings/interest_account_form.html
<form method="post" hx-post="{% url 'savings:add_interest_account' %}" hx-target="#dynamic-content" 
    hx-swap="innerHTML">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% if messages %}
    <div class="alert alert-success mt-2">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}

savings/templates/savings/oracle_savings_transactions.html
{% extends 'base.html' %}

{% block content %}

<h3 class="mb-4">{{ title }} Transactions</h3>

<a href="{% url 'savings:download_oracle_savings_excel' %}">Download Excel</a> |
<a href="{% url 'savings:download_oracle_savings_pdf' %}">Download PDF</a>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Month</th>
      <th scope="col">Name</th>
      <th scope="col">Payment Type</th>
      <th scope="col">Normal Savings</th>
      <th scope="col">Divine Touch</th>
      <th scope="col">SP SAV</th>
      <th scope="col">RSS</th>
      <th scope="col">Loan Repay</th>
      <th scope="col">Interest</th>
      <th scope="col">Commod</th>
      <th scope="col">Received</th>
    </tr>
  </thead>
  <tbody>
    {% for transaction in transactions %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ transaction.get_month_display }}</td>
        <td>{{ transaction.owner.first_name }} {{ transaction.owner.last_name }}</td>
        <td>{{ transaction.payment_type }}</td>
        <td>{{ transaction.normal_savings }}</td>
        <td>{{ transaction.divine_touch }}</td>
        <td>{{ transaction.sp_sav }}</td>
        <td>{{ transaction.rss }}</td>
        <td>{{ transaction.loan_repay }}</td>
        <td>{{ transaction.interest }}</td>
        <td>{{ transaction.commod }}</td>
        <td>{{ transaction.received }}</td>
      </tr>
    {% endfor %}
    <tr>
      <th scope="row">Total</th>
      <td></td>
      <td></td>
      <td>{{ transactions_sum }}</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

{% endblock content %}

savings/templates/savings/savings.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">

  {% if messages %}
    <div class="alert alert-info">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <h2 class="text-center">Savings Account Management</h2>

  <!-- Instructions Section -->
  <div class="alert alert-info mb-4">
    <strong>Instructions:</strong> 
    <ul>
      <li>The "Upload" button is for uploading the required data using the Excel template. Please fill out the template and upload it here.</li>
      <li>If you decide not to upload the required data, the "Account Operations" button allows you to enter the necessary data for each member using the application form.</li>
      <li>The "Edit" button allows you to correct any mistakes in the data for a particular month.</li>
    </ul>
  </div>

  <div class="row p-3 mt-3">
    <!-- Operations Section -->
    <div class="col-md-6">
      <h4>Operations</h4>
      <h3><a hx-get="{% url 'savings:deposit' %}" hx-target="#dynamic-content" class="btn btn-outline-info">Account Operations</a></h3>
      <h3><a class="btn btn-outline-info" hx-get="{% url 'savings:edit_saving_account' %}" hx-target="#dynamic-content">Edit</a></h3>
      <h3><a class="btn btn-outline-info" hx-get="{% url 'savings:upload_savings' %}" hx-target="#dynamic-content">Upload</a></h3>
      <h3>
          <a class="btn btn-outline-info" hx-get="{% url 'reports:bulk_delete_records' %}" hx-target="#dynamic-content">
              <i class="fas fa-trash-alt me-2"></i>Bulk Delete
          </a>
      </h3>
      <h3><a class="btn btn-outline-info invisible" hx-get="{% url 'savings:add_commodity_account' %}" hx-target="#dynamic-content">Commodity</a></h3>
      <h3><a class="btn btn-outline-info invisible" hx-get="{% url 'savings:add_loan_account' %}" hx-target="#dynamic-content">Loan</a></h3>
    </div>

    <!-- Transactions Section (Invisible for now) -->
    <div class="col-md-6 invisible">
      <h4>Transactions</h4>
      <h3><a hx-get="{% url 'savings:transactions' %}" hx-target="#dynamic-content" class="btn btn-outline-primary">All Deposit Transactions</a></h3>
      <h3><a hx-get="{% url 'savings:teller_savings_transactions' %}" hx-target="#dynamic-content" class="btn btn-outline-primary">Teller Transactions</a></h3>
      <h3><a hx-get="{% url 'savings:oracle_savings_transactions' %}" hx-target="#dynamic-content" class="btn btn-outline-primary">Oracle Transactions</a></h3>
    </div>
  </div>

</div>

{% endblock %}

savings/templates/savings/savings_transactions.html
{% extends 'base.html' %}

{% block content %}
<h3 class="mb-4">{{ title }} Transactions</h3>

<div class="btn-group mb-3">
    <a href="{% url 'savings:download_all_savings_excel' %}" class="btn btn-success">Download Excel</a>
    <a href="{% url 'savings:download_all_savings_pdf' %}" class="btn btn-success">Download PDF</a>
</div>

<div class="transactions-container">
  {% for transaction in transactions %}
    <div class="transaction-card card mb-3 p-3">
      <h5>{{ transaction.owner.first_name }} {{ transaction.owner.last_name }}</h5>
      <ul class="list-unstyled">
        <li><strong>Month:</strong> {{ transaction.get_month_display }}</li>
        <li><strong>Received:</strong> {{ transaction.received }}</li>
        <li><strong>Savings Balance:</strong> {{ transaction.savings_balance }}</li>
        <li><strong>Interest Balance:</strong> {{ transaction.interest_balance }}</li>
        <li><strong>Loan Balance:</strong> {{ transaction.loan_balance }}</li>
        <li><strong>Commodity Balance:</strong> {{ transaction.commod_balance }}</li>
        <li><strong>RSS Balance:</strong> {{ transaction.rss_balance }}</li>
        <li><strong>Divine Touch Balance:</strong> {{ transaction.divine_touch_balance }}</li>
        <li><strong>Share Balance:</strong> {{ transaction.share_balance }}</li>
      </ul>
    </div>
  {% endfor %}
</div>

<style>
  .transactions-container {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }

  .transaction-card {
    border-radius: 8px;
    border: 1px solid #e0e0e0;
  }

  @media (max-width: 768px) {
    .transaction-card {
      padding: 1rem;
    }
  }
</style>
{% endblock %}

savings/templates/savings/savings_upload.html
<div class="container mt-4">
    <!-- Instructions Section -->
    <div class="alert alert-info d-flex align-items-center mb-4">
      <i class="bi bi-info-circle me-2 fs-5"></i>
      <div>
        <strong>Instructions:</strong> Before uploading, download the Excel template using the button below, fill it out with the required data, and then upload the completed file.
      </div>
    </div>
  
    <!-- Form Section -->
    <form method="POST" hx-post="{% url 'savings:upload_savings' %}" enctype="multipart/form-data" hx-target="#dynamic-content" class="form-group shadow p-4 bg-white rounded">
      {% csrf_token %}
  
      <!-- Month Selection -->
      <div class="mb-3">
        <label for="month" class="form-label">Select Month:</label>
        <select name="month" class="form-control" required>
          <option value="">-- Select Month --</option>
          {% for value, name in months %}
            <option value="{{ value }}" {% if value == current_month %}selected{% endif %}>{{ name }}</option>
          {% endfor %}
        </select>
      </div>
  
      <!-- Year Selection -->
      <div class="mb-3">
        <label for="year" class="form-label">Select Year:</label>
        <select name="year" class="form-control" required>
          <option value="">-- Select Year --</option>
          {% for year in years %}
            <option value="{{ year }}" {% if year == current_year %}selected{% endif %}>{{ year }}</option>
          {% endfor %}
        </select>
      </div>
  
      <!-- File Upload -->
      <div class="mb-4">
        <label for="file" class="form-label fw-semibold">Upload Excel File</label>
        <input type="file" name="file" id="file" class="form-control" required>
        <small class="text-muted">Ensure the file is in the correct format as per the template.</small>
      </div>
  
      <!-- Submit and Download Buttons -->
      <div class="d-flex flex-column flex-md-row justify-content-between gap-3">
        <button type="submit" class="btn btn-primary px-4">Upload</button>
        <a href="{% url 'savings:download_template' %}" class="btn btn-success px-4">
          <i class="bi bi-download me-1"></i>Download Template
        </a>
      </div>
    </form>
  
    <!-- Display Messages -->
    {% if messages %}
      <div class="alert alert-info mt-4">
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %}
      </div>
    {% endif %}
  </div>
  

savings/templates/savings/teller_savings_transactions.html
{% extends 'base.html' %}

{% block content %}

<h3 class="mb-4">{{ title }} Transactions</h3>

<a href="{% url 'savings:download_teller_savings_excel' %}">Download Excel</a> |
<a href="{% url 'savings:download_teller_savings_pdf' %}">Download PDF</a>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Month</th>
      <th scope="col">Name</th>
      <th scope="col">Payment Type</th>
      <th scope="col">Normal Savings</th>
      <th scope="col">Divine Touch</th>
      <th scope="col">SP SAV</th>
      <th scope="col">RSS</th>
      <th scope="col">Loan Repay</th>
      <th scope="col">Interest</th>
      <th scope="col">Commod</th>
      <th scope="col">Received</th>
    </tr>
  </thead>
  <tbody>
    {% for transaction in transactions %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ transaction.get_month_display }}</td>
        <td>{{ transaction.owner.first_name }} {{ transaction.owner.last_name }}</td>
        <td>{{ transaction.payment_type }}</td>
        <td>{{ transaction.normal_savings }}</td>
        <td>{{ transaction.divine_touch }}</td>
        <td>{{ transaction.sp_sav }}</td>
        <td>{{ transaction.rss }}</td>
        <td>{{ transaction.loan_repay }}</td>
        <td>{{ transaction.interest }}</td>
        <td>{{ transaction.commod }}</td>
        <td>{{ transaction.received }}</td>
        <td>
          <a hx-get="{% url 'savings:delete_transaction' transaction.pk %}" hx-target="#modalBody" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">Delete</a>
        </td>
      </tr>
    {% endfor %}
    <tr>
      <th scope="row">Total</th>
      <td></td>
      <td></td>
      <td>{{ transactions_sum }}</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

{% endblock content %}

savings/templates/savings/transaction_confirm_delete.html
<h3>Confirm Deletion</h3>
<p>Are you sure you want to delete this transaction?</p>
Precious

{% if messages %}
    <div class="alert alert-info">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}

<form method="POST" hx-post="{% url 'savings:delete_transaction' transaction.pk %}" hx-target="#modalBody" 
    hx-swap="innerHTML">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Confirm</button>
  <!-- <a hx-get="{% url 'savings:transactions' %}" hx-target="#dynamic-content" class="btn btn-secondary">Cancel</a> -->
</form>

savings/templates/savings/yearly_savings_report.html
{% extends 'base.html' %}

{% block content %}

<h3 class="mb-4">{{ title }} Transactions</h3>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Year</th>
      <th scope="col">Name</th>
      <th scope="col">Savings</th>
      <th scope="col">Divine Touch</th>
      <th scope="col">SP SAV</th>
      <th scope="col">RSS</th>
      <th scope="col">Loan Repay</th>
      <th scope="col">Interest</th>
      <th scope="col">Commod</th>
      <th scope="col">Received</th>
    </tr>
  </thead>
  <tbody>
    {% for transaction in transactions %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ transaction.get_month_display }}</td>
        <td>{{ transaction.owner.first_name }} {{ transaction.owner.last_name }}</td>
        <td>{{ transaction.savings }}</td>
        <td>{{ transaction.loan }}</td>
        <td>{{ transaction.loan_balance }}</td>
        <td>{{ transaction.divine_touch }}</td>
        <td>{{ transaction.sp_sav }}</td>
        <td>{{ transaction.rss }}</td>
        <td>{{ transaction.loan_repay }}</td>
        <td>{{ transaction.interest }}</td>
        <td>{{ transaction.commod }}</td>
        <td>
          <a hx-get="{% url 'savings:delete_transaction' transaction.pk %}" hx-target="#modalBody" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">Delete</a>
        </td>
      </tr>
    {% endfor %}
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

{% endblock content %}